UPDATE `FileAsset`
SET `kind` = 'CHEMICAL_IMAGE'
WHERE `kind` = 'CHEMICAL_3D_IMAGE';

ALTER TABLE `FileAsset`
  MODIFY `kind` ENUM('CHEMICAL_IMAGE', 'PROTOCOL_VIDEO', 'PROTOCOL_ATTACHMENT', 'RUN_ATTACHMENT') NOT NULL;
